
# The url for the app to be served under

app_host = "0.0.0.0:5003"

# A list of base URLs to be used throughout the application. In development, url's
# can change all the time, so it is made easy here to modify them, and they are
# used throughout the application.

[base_urls]
lv_release_score = "http://localhost:5002"